version: "3.0"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - blog-network
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
